import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ posts }: { posts: any }) {
  console.log(posts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Posts</h1>
        <div>
          {posts.map((post: any) => (
            <div key={post.id}>
              <h2>{post.title.rendered}</h2>
              <p>{post.content.rendered}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(`${process.env.WORDPRESS_API}/wp-json/wp/v2/posts`);
  const posts = await res.json();

  return { props: { posts } };
};
